<a class="ajax link add" title="<?php echo t('add question'); ?>" href="<?php echo $this->baseUrl('/question/add') ?>">
	<?php echo t('add question'); ?>
</a>

<?php if (!$this->questions || $this->questions->count() == 0): ?>
    <p><?php echo t('Er zijn nog geen vragen aangemaakt'); ?></p>
<?php else: ?>
    <table>
        <thead>
            <tr>
                <th><?php echo t('question'); ?></th>
                <th><?php echo t('date added'); ?></th>
                <th><?php echo t('used in questionnaires'); ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->questions as $question): ?>
                <tr>
                    <td>
                        <?php echo $question->getQuestionText()->text; ?>
                    </td>
                    <td>
                        <?php
                            $date = new Zend_Date($question->created);
                            echo $date->get(Zend_Date::DATETIME);
                        ?>
                    </td>
                    <td>
                        <?php foreach ($question->getQuestionnaires() as $q): ?>
                            <a href="<?php echo $this->baseUrl('/questionnaire/edit/id/' . $q->id); ?>"><?php echo $q->id; ?></a>
                        <?php endforeach;?>
                    </td>
                    <td>
                        <a class="ajax icon edit" title="<?php echo t('bewerken'); ?>" href="<?php echo $this->baseUrl("/question/edit/id/" . $question->id);    ?>">&nbsp;</a>
                        <?php if($question->QuestionnaireQuestion->count() == 0): ?>
                            <a class="ajax icon delete" title="<?php echo t('verwijderen'); ?>" href="<?php echo $this->baseUrl("/question/delete/id/" . $question->id); ?>">&nbsp;</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>