<reportConfig>
    <reportId><?php echo $this->report->id; ?></reportId>
    <xformName>questionnaire</xformName>
    <!--  todo improve servername/pathToApplication  (https) -->
    <xformLocation>http://<?php echo $_SERVER['SERVER_NAME']; echo $this->baseUrl("questionnaire/xform/id/"); echo $this->report->questionnaire_id; ?></xformLocation>
    <dataLocation>http://<?php echo $_SERVER['SERVER_NAME']; echo $this->baseUrl("questionnaire/xform-data/id/"); echo $this->report->questionnaire_id; ?></dataLocation>
    <reportDefinitionLocation>http://<?php echo $_SERVER['SERVER_NAME']; echo $this->baseUrl("report/jrxml/id/"); echo $this->report->id; ?></reportDefinitionLocation>
    <customer><?php echo $this->report->customer; ?></customer>
    <language><?php echo $this->report->language; ?></language>
    <splitQuestionId><?php if ($this->report->QuestionnaireQuestion) echo $this->report->QuestionnaireQuestion->getXPath(); ?></splitQuestionId>
    <outputDir><?php echo $this->report->output_dir; ?></outputDir>
    <outputFileName><?php echo $this->report->output_name; ?></outputFileName>
    <outputFormat><?php echo $this->report->output_format; ?></outputFormat>
</reportConfig>