<?php if ($this->output): ?>
    <div>
        <p>Er is een probleem opgetreden bij het genereren van het rapport. Zie onderstaande melding voor details.</p>
        <pre><?php echo $this->output; ?></pre>
    </div>
<?php endif; ?>

<?php if (is_string($this->file)): ?>
    <div>
        <p>Het rapport is gegenereerd en opgeslagen. Klik op onderstaande link om het rapport te bekijken.</p>
        <a href="<?php echo $this->baseUrl($this->file); ?>">
            <?php echo $this->file; ?>
        </a>
    </div>
<?php endif; ?>

<?php if (is_array($this->file)): ?>
    <div>
        <p>De rapporten zijn gegenereerd. Klik op onderstaande links om de rapporten te bekijken.</p>
        <ul>
        <?php foreach ($this->file as $file):
        	$file=trim($file); 
        	if (!empty($file)): ?> 
            <li>
                <a href="<?php echo $this->baseUrl($file); ?>">
                    <?php echo $file; ?>
                </a>
            </li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>