<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="report1DocentRapport" pageWidth="<?php echo $this->pageWidth; ?>" pageHeight="<?php echo $this->pageHeight; ?>" orientation="<?php echo $this->pageOrientation; ?>" whenNoDataType="AllSectionsNoDetail" columnWidth="<?php echo $this->columnWidth; ?>" leftMargin="<?php echo $this->leftMargin; ?>" rightMargin="<?php echo $this->rightMargin; ?>" topMargin="<?php echo $this->topMargin; ?>" bottomMargin="<?php echo $this->bottomMargin; ?>" isFloatColumnFooter="true" whenResourceMissingType="Key">
	<property name="ireport.zoom" value="1.5"/>
	<property name="ireport.x" value="15"/>
	<property name="ireport.y" value="0"/>
	<template><![CDATA[$P{DEFAULT_STYLE_FILE}]]></template>
	<scriptlet name="GetXformLabel" class="it.bisi.report.jasper.scriptlet.GetXformLabel">
		<scriptletDescription><![CDATA[getXform label]]></scriptletDescription>
	</scriptlet>
	<parameter name="QUERY" class="java.lang.String" isForPrompting="false">
		<defaultValueExpression><![CDATA[]]></defaultValueExpression>
	</parameter>
	<parameter name="DEFAULT_STYLE_FILE" class="java.lang.String" isForPrompting="false">
		<defaultValueExpression><![CDATA["org/webenq/resources/defaultStyle.jrtx"]]></defaultValueExpression>
	</parameter>
	<parameter name="SUBREPORT_DIR" class="java.lang.String" isForPrompting="false">
		<defaultValueExpression><![CDATA["org/webenq/resources/"]]></defaultValueExpression>
	</parameter>
	<parameter name="CUSTOMER" class="java.lang.String" isForPrompting="false"/>
	<parameter name="SPLIT_QUESTION_ID" class="java.lang.String" isForPrompting="false"/>
	<parameter name="SPLIT_QUESTION_VALUE" class="java.lang.String" isForPrompting="false"/>
	<parameter name="REPORT_IDENTIFIER" class="java.lang.String" isForPrompting="false"/>
	<parameter name="XFORM_LOCATION" class="java.lang.String" isForPrompting="false"/>
	<parameter name="QUESTION_ID" class="java.lang.String" />
	<parameter name="FORM_NAME" class="java.lang.String" isForPrompting="false"/>
	<parameter name="DATA_LOCATION" class="java.lang.String"/>
	<parameter name="DOC_DATA" class="java.lang.String" isForPrompting="false"/>
	<parameter name="COLOR_RANGE_MAP" class="java.util.HashMap"/>
	<parameter name="SPLIT_QUESTION_LABEL" class="java.lang.String" isForPrompting="false"/>
	<queryString>
		<![CDATA[]]>
	</queryString>
	
	
    <?php
        echo $this->render('report/jrxml/title.phtml');
        echo $this->render('report/jrxml/pageHeader.phtml');
        echo $this->render('report/jrxml/columnHeader.phtml');
        echo $this->render('report/jrxml/detail.phtml');
        //echo $this->render('report/jrxml/columnFooter.phtml');
        //echo $this->render('report/jrxml/pageFooter.phtml');
        //echo $this->render('report/jrxml/summary.phtml');
    ?>
</jasperReport>