<a class="link download" href="<?php echo $this->baseUrl('report/control/id/' . $this->report->id) ?>" title="<?php echo t('download control file'); ?>">
    <?php echo t('download control file'); ?>
</a>

<a class="link download" href="<?php echo $this->baseUrl('report/jrxml/id/' . $this->report->id) ?>" title="<?php echo t('download jrxml'); ?>">
    <?php echo t('download jrxml'); ?>
</a>
<a class="link report"  href="<?php echo $this->baseUrl('report/generate/id/' .$this->report->id) ?>" title="<?php echo t('generate report'); ?>"><?php echo t('generate report'); ?></a>


<h2>
    <?php echo t('Report'); ?>
    "<?php echo $this->report->getReportTitle()->text; ?>"
    <?php echo t('for questionnaire'); ?>
    "<?php echo $this->report->Questionnaire->getQuestionnaireTitle()->text; ?>"
</h2>

<a class="ajax link add" href="<?php echo $this->baseUrl('report-element/add/report/' . $this->report->id) ?>" title="<?php echo t('add report element'); ?>">
    <?php echo t('add report element'); ?>
</a>

<ul class="sortable">
    <?php foreach ($this->report->ReportElement as $element): ?>
    	<li id="re_<?php echo $element->id; ?>">
    	    <?php echo $this->reportElement($element); ?>
	    </li>
	<?php endforeach; ?>
</ul>