<?php if ($this->questionnaire->QuestionnaireQuestion && $this->questionnaire->QuestionnaireQuestion->count() > 0): ?>
	<table>
		<thead>
			<tr>
				<th>vraag</th>
				<th>type</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->questionnaire->QuestionnaireQuestion as $questionnaireQuestion): ?>
				<?php $meta = unserialize($questionnaireQuestion->meta); ?>
				<tr>
					<td>
						<?php echo $questionnaireQuestion->Question->QuestionText[0]->text; ?>
					</td>
					<td>
						<?php if (isset($meta['class']))
							echo $meta['class'];
						?>
					</td>
					<td>
						<a href="<?php echo $this->baseUrl("/management/edit/id/" . $questionnaireQuestion->id); ?>">
							bewerken
						</a>					
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>