<a class="link add ajax" href="<?php echo $this->baseUrl("/answer-possibility-group/add"); ?>" title="<?php echo t('add answer possibility group'); ?>">
    <?php echo t('add answer possibility group'); ?>
</a>

<?php if (!$this->answerPossibilityGroups || $this->answerPossibilityGroups->count() == 0): ?>
    <p><?php echo t('There aren\'t any answer possibilities yet'); ?></p>
<?php else: ?>
    <table>
        <thead>
            <tr>
                <th><?php echo t('group'); ?></th>
                <th><?php echo t('allowed'); ?></th>
                <th><?php echo t('used'); ?></th>
                <th><?php echo t('questionnaire(s)'); ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->answerPossibilityGroups as $answerPossibilityGroup): ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->baseUrl("/answer-possibility-group/edit/id/" . $answerPossibilityGroup->id);    ?>">
                            <?php echo $answerPossibilityGroup->name; ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->baseUrl("/answer-possibility-group/edit/id/" . $answerPossibilityGroup->id);    ?>">
                            <?php echo $answerPossibilityGroup->number; ?>
                            <?php echo t('possibilities'); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->baseUrl("/answer-possibility-group/edit/id/" . $answerPossibilityGroup->id);    ?>">
                            <?php echo $answerPossibilityGroup->AnswerPossibility->count(); ?>
                            <?php echo t('possibilities'); ?>
                        </a>
                    </td>
                    <td>
                        <?php
                            $usedIn = array();
                            foreach ($answerPossibilityGroup->QuestionnaireQuestion as $qq):
                                $usedIn[] = $qq->Questionnaire->id;
                            endforeach;
                            $usedIn = array_unique($usedIn);
                            sort($usedIn);
                            foreach ($usedIn as $id):
                        ?>
                                <a href="<?php echo $this->baseUrl("/questionnaire/edit/id/" . $id);    ?>"><?php echo $id; ?></a>
                        <?php
                            endforeach;
                        ?>
                    </td>
                    <td>
                        <a class="icon edit" title="<?php echo t('edit'); ?>" href="<?php echo $this->baseUrl("/answer-possibility-group/edit/id/" . $answerPossibilityGroup->id);    ?>">&nbsp;</a>
                        <?php if ($answerPossibilityGroup->QuestionnaireQuestion->count() == 0): ?>
                            <a class="icon delete" title="<?php echo t('delete'); ?>" href="<?php echo $this->baseUrl("/answer-possibility-group/delete/id/" . $answerPossibilityGroup->id);    ?>">&nbsp;</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>