<a class="icon add" title="<?php echo _('antwoordmogelijkhedengroep toevoegen'); ?>" href="<?php echo $this->baseUrl("/answer-possibility-group/add"); ?>">&nbsp;</a>
<a href="<?php echo $this->baseUrl("/answer-possibility-group/add"); ?>">
	<?php echo _('antwoordmogelijkhedengroep toevoegen'); ?>
</a>

<?php if (!$this->answerPossibilityGroups || $this->answerPossibilityGroups->count() == 0): ?>
	<p><?php echo _('Er zijn nog geen antwoordmogelijkheden'); ?></p>
<?php else: ?>
	<table>
		<thead>
			<tr>
				<th><?php echo _('groep'); ?></th>
				<th><?php echo _('mogelijkheden'); ?></th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->answerPossibilityGroups as $answerPossibilityGroup): ?>
				<tr>
					<td>
						<a href="<?php echo $this->baseUrl("/answer-possibility-group/edit/id/" . $answerPossibilityGroup->id);	?>">
							<?php echo $answerPossibilityGroup->name; ?>
						</a>
					</td>
					<td>
						<a href="<?php echo $this->baseUrl("/answer-possibility-group/edit/id/" . $answerPossibilityGroup->id);	?>">
							<?php echo $answerPossibilityGroup->AnswerPossibility->count(); ?>
							<?php echo _('mogelijkheden'); ?>
						</a>
					</td>
					<td>
						<a class="icon edit" title="<?php echo _('bewerken'); ?>" href="<?php echo $this->baseUrl("/answer-possibility-group/edit/id/" . $answerPossibilityGroup->id);	?>">&nbsp;</a>
						<?php if ($answerPossibilityGroup->QuestionnaireQuestion->count() == 0): ?>
							<a class="icon delete" title="<?php echo _('verwijderen'); ?>" href="<?php echo $this->baseUrl("/answer-possibility-group/delete/id/" . $answerPossibilityGroup->id);	?>">&nbsp;</a>
						<?php endif; ?>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>