<div class="tabs">
    <?php
    //tabs based on subforms
        echo $this->tabsBasedOnSubForms();
    ?>

    <div id=questionText><h3>
    <?php
    $language = Zend_Registry::get('Zend_Locale')->getLanguage();
        if ($this->form->question){
            $temp=$this->form->question->getValue('text');
            echo $temp[$language];
        }elseif($this->form->grid){
            $temp=$this->form->grid->getValue('text');
            echo $temp[$language];
        }
        ?>
    </h3></div>
    <?php
        echo $this->form;
    ?>
</div>