<form action="<?php echo $this->form->getAction(); ?>" method="post">
    <div class="tabs">
        <ul>
            <li>
                <a href="#question"><?php echo t('question'); ?></a>
            </li>
            <li>
                <a href="#answers"><?php echo t('answer options'); ?></a>
            </li>
            <li>
                <a href="#options"><?php echo t('options'); ?></a>
            </li>
            <li>
                <a href="#debug">debug: defaults</a>
            </li>
        </ul>
        <div id=questionText><h3>

        <?php // @todo next should get text in stead of name?>
        <?php echo $this->questionnaireQuestion->QuestionnaireElement->getTranslation('text'); ?>
        <?php //echo $this->questionnaireQuestion->QuestionnaireElement->getTranslation('text'); ?>
        </h3></div>
        <div id="question">
            <?php echo $this->form->question; ?>
        </div>
        <div id="answers">
            <?php echo $this->form->answers; ?>
        </div>
        <div id="options">
            <?php echo $this->form->options; ?>
        </div>
        <div id="debug">
            <?php echo $this->form->debug; ?>
        </div>
    </div>
</form>