<div class="tabs">
    <form action="<?php echo $this->form->getAction(); ?>" method="post">
        <ul>
            <li>
                <a href="#general"><?php echo t('general'); ?></a>
            </li>
            <li>
                <a href="#answer"><?php echo t('answer possibilities'); ?></a>
            </li>
            <li>
                <a href="#validation"><?php echo t('validation'); ?></a>
            </li>
        </ul>
        <div id="general">
            <?php echo $this->form->general; ?>
        </div>
        <div id="answer">
            <?php echo $this->form->answers; ?>
        </div>
        <div id="validation">
            <?php echo $this->form->validation; ?>
        </div>
    </form>
</div>
