<div class="tabs">
    <form action="<?php echo $this->form->getAction(); ?>" method="post">
        <ul>
            <li>
                <a href="#question"><?php echo t('question'); ?></a>
            </li>
            <li>
                <a href="#answerOptions"><?php echo t('answer options'); ?></a>
            </li>
            <li>
                <a href="#options"><?php echo t('options'); ?></a>
            </li>
        </ul>
        <div id=questionText><h3>

        <?php // @todo next should get text in stead of name?>
        <?php echo $this->questionnaireQuestion->QuestionnaireElement->name; ?>
        <?php //echo $this->questionnaireQuestion->QuestionnaireElement->getTranslation('text'); ?>
        </h3></div>
        <div id="question">
            <?php echo $this->form->question; ?>
        </div>
        <div id="answerOptions">
            <?php echo $this->form->answerOptions; ?>
        </div>
        <div id="options">
            <?php echo $this->form->options; ?>
        </div>
    </form>
</div>
