<band height="20" splitType="Prevent">
<subreport>
	<reportElement positionType="Float" x="0" y="0" width="<?php echo $this->columnWidth; ?>" height="20" isRemoveLineWhenBlank="true" />
    <?php if (isset($this->data['report_qq_ids'])): ?>
    	<subreportParameter name="SUBREPORT_DIR">
        	<subreportParameterExpression><![CDATA[$P{SUBREPORT_DIR}]]></subreportParameterExpression>
        </subreportParameter>
    	<subreportParameter name="CUSTOMER">
    		<subreportParameterExpression><![CDATA[$P{CUSTOMER}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="DEFAULT_STYLE_FILE">
    		<subreportParameterExpression><![CDATA[$P{DEFAULT_STYLE_FILE}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="REPORT_RESOURCE_BUNDLE">
    		<subreportParameterExpression><![CDATA[$P{REPORT_RESOURCE_BUNDLE}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="DATA_LOCATION">
             <subreportParameterExpression><![CDATA[$P{DATA_LOCATION}]]></subreportParameterExpression>
        </subreportParameter>
    	<subreportParameter name="XFORM_LOCATION">
    		<subreportParameterExpression><![CDATA[$P{XFORM_LOCATION}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="FORM_NAME">
    		<subreportParameterExpression><![CDATA[$P{FORM_NAME}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="CROSSTAB_HEADER_TEXT_ID">
    		<subreportParameterExpression>
    			<![CDATA["<?php echo $this->element->getXpath($this->data['header_qq_id']); ?>"]]>
    		</subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="COLOR_MEAN">
			<subreportParameterExpression>
			<![CDATA["<?php if (isset($this->data['color_mean'])) echo $this->data['color_mean'];  ?>"]]>
			</subreportParameterExpression>
		</subreportParameter>
		<subreportParameter name="SCALE_QUESTION_INFO">
			<subreportParameterExpression><![CDATA["<?php
			$scaleQuestionInfo=Webenq_Model_ReportElement::getScaleType($this->data['report_qq_ids']);
			foreach ($scaleQuestionInfo  as $id=>$scaleType){
				$xpaths[$this->element->getXpath($id)]=$scaleType;
			}
			echo addslashes($this->json($xpaths));?>"]]></subreportParameterExpression>
		</subreportParameter>
		<subreportParameter name="RECODE_COLOR_MAP">
			<subreportParameterExpression><![CDATA[$P{RECODE_COLOR_MAP}]]></subreportParameterExpression>
		</subreportParameter>
		<subreportParameter name="NO_BARCHART">
                    <subreportParameterExpression><![CDATA[<?php echo isset($this->data['no_barchart']) && !empty($this->data['no_barcharts']) ? '"'.$this->data['no_barcharts'].'"' : '""' ; ?>]]></subreportParameterExpression>
                </subreportParameter>
    	<dataSourceExpression>
    		<![CDATA[new it.bisi.report.jasper.datasource.XformJRDataSource(
    			$P{DATA_LOCATION},
    			$P{XFORM_LOCATION},
    			$P{FORM_NAME},
    			"<?php
    			    $xpaths = array();
    			    foreach ($this->data['report_qq_ids'] as $id)
    			        $xpaths[] = $this->element->getXpath($id);
    			    echo implode(',', $xpaths);
    		    ?>",
    			<?php echo isset($this->data['group_qq_id'])&& !empty($this->data['group_qq_id']) ? '"' . $this->element->getXpath($this->data['group_qq_id']) . '"' : 'null'; ?>,
    			$P{SPLIT_QUESTION_ID},
    			$P{SPLIT_QUESTION_VALUE},false
    			).getRecords()
			]]>
    	</dataSourceExpression>
    	<?php if ($this->pageOrientation =='Portrait') {
	echo '<subreportExpression><![CDATA[$P{SUBREPORT_DIR}+"report7-barchart.jasper"]]></subreportExpression>';
    	}else {
    echo '<subreportExpression><![CDATA[$P{SUBREPORT_DIR}+"report7-barchart-land.jasper"]]></subreportExpression>';
    	} ?>
	<?php endif; ?>
</subreport>
</band>