<band height="20" splitType="Prevent">
<subreport isUsingCache="false">
	<reportElement 	positionType="Float" x="0" y="0" width="<?php echo $this->columnWidth; ?>" height="20" 	isRemoveLineWhenBlank="true" />
	<subreportParameter name="CUSTOMER">
		<subreportParameterExpression>	<![CDATA[$P{CUSTOMER}]]></subreportParameterExpression>
	</subreportParameter>
	<subreportParameter name="DEFAULT_STYLE_FILE">
		<subreportParameterExpression><![CDATA[$P{DEFAULT_STYLE_FILE}]]></subreportParameterExpression>
	</subreportParameter>
	<subreportParameter name="Q_TEXT">
		<subreportParameterExpression><![CDATA[]]></subreportParameterExpression>
	</subreportParameter>
 	<subreportParameter name="REPORT_RESOURCE_BUNDLE">
		<subreportParameterExpression><![CDATA[$P{REPORT_RESOURCE_BUNDLE}]]></subreportParameterExpression>
	</subreportParameter>
 	<dataSourceExpression>
 		<![CDATA[new net.sf.jasperreports.engine.JREmptyDataSource()]]></dataSourceExpression>
	<subreportExpression>
		<![CDATA["<?php echo $this->data['filename']; ?>"]]>
	</subreportExpression>
</subreport>
</band>