<band height="20" splitType="Prevent">
<subreport>
	<reportElement positionType="Float" x="0" y="0" width="<?php echo $this->columnWidth; ?>" height="20" isRemoveLineWhenBlank="true" />
    <?php if (isset($this->data['report_qq_id'])): ?>
    	<subreportParameter name="CUSTOMER">
    		<subreportParameterExpression><![CDATA[$P{CUSTOMER}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="DEFAULT_STYLE_FILE">
    		<subreportParameterExpression><![CDATA[$P{DEFAULT_STYLE_FILE}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="REPORT_RESOURCE_BUNDLE">
    		<subreportParameterExpression><![CDATA[$P{REPORT_RESOURCE_BUNDLE}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="DISPLAY_GROUP_QUESTION_TEXT">
			<subreportParameterExpression>
			<![CDATA["<?php if (isset($this->data['display_group_question_text'])) echo $this->data['display_group_question_text'];  ?>"]]>
			</subreportParameterExpression>
		</subreportParameter>
    	<dataSourceExpression>
    		<![CDATA[new it.bisi.report.jasper.datasource.XformJRDataSource(
    			$P{DATA_LOCATION},
    			$P{XFORM_LOCATION},
    			$P{FORM_NAME},
    			"<?php echo $this->element->getXpath($this->data['report_qq_id']); ?>",
    			<?php echo isset($this->data['group_qq_id']) && !empty($this->data['group_qq_id']) ? '"' . $this->element->getXpath($this->data['group_qq_id']) . '"' : 'null'; ?>,
    			$P{SPLIT_QUESTION_ID},
    			$P{SPLIT_QUESTION_VALUE},
    			true).getRecords()
    		]]>
    	</dataSourceExpression>
    	<?php
    	if (!isset($this->data['variant'])) {
			$this->data['variant']="";
		}
    	switch ($this->data['variant']){
		case 'labelsNotRotated':
		default:
    		if ($this->pageOrientation =='Portrait') {
				echo '<subreportExpression><![CDATA[$P{SUBREPORT_DIR}+"report2-freq-notRotated.jasper"]]></subreportExpression>';
    		}else{
				echo '<subreportExpression><![CDATA[$P{SUBREPORT_DIR}+"report2-freq-land-notRotated.jasper"]]></subreportExpression>';
			}
			break;
		case 'labelsRotated':
			if ($this->pageOrientation =='Portrait') {
				echo '<subreportExpression><![CDATA[$P{SUBREPORT_DIR}+"report2-freq-rotated.jasper"]]></subreportExpression>';
			}else{
				echo '<subreportExpression><![CDATA[$P{SUBREPORT_DIR}+"report2-freq-land-rotated.jasper"]]></subreportExpression>';
			}
		break;
		}?>

	<?php endif; ?>
</subreport>
</band>