<subreport>
	<reportElement positionType="Float" x="0" y="<?php echo $this->y; ?>" width="555" height="20" isRemoveLineWhenBlank="true" />
	<?php if (isset($this->data['report_qq_id'])): ?>
    	<subreportParameter name="CUSTOMER">
    		<subreportParameterExpression><![CDATA[$P{CUSTOMER}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="DEFAULT_STYLE_FILE">
    		<subreportParameterExpression><![CDATA[$P{DEFAULT_STYLE_FILE}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="REPORT_RESOURCE_BUNDLE">
    		<subreportParameterExpression><![CDATA[$P{REPORT_RESOURCE_BUNDLE}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="XFORM_LOCATION">
    		<subreportParameterExpression><![CDATA[$P{XFORM_LOCATION}]]></subreportParameterExpression>
    	</subreportParameter>
    	<subreportParameter name="FORM_NAME">
    		<subreportParameterExpression><![CDATA[$P{FORM_NAME}]]></subreportParameterExpression>
    	</subreportParameter>
    	  	<dataSourceExpression>
    		<![CDATA[new it.bisi.report.jasper.datasource.XformJRDataSource(
    			$P{DATA_LOCATION},
    			$P{XFORM_LOCATION},
    			$P{FORM_NAME},
    			"<?php echo $this->element->getXpath($this->data['report_qq_id']); ?>",
    			<?php echo isset($this->data['group_qq_id']) && !empty($this->data['group_qq_id']) ? '"' . $this->element->getXpath($this->data['group_qq_id']) . '"' : 'null'; ?>,
    			$P{SPLIT_QUESTION_ID},
    			$P{SPLIT_QUESTION_VALUE},
    			false).getRecords()
    		]]>
    	</dataSourceExpression>
    	<subreportExpression><![CDATA[$P{SUBREPORT_DIR}+"report8-response.jasper"]]></subreportExpression>
	<?php endif; ?>
</subreport>