<subreport>
	<reportElement positionType="Float" x="0" y="<?php echo $this->y; ?>" width="555" height="20" isRemoveLineWhenBlank="true"> 
	<?php echo (isset($this->data['report_for_subgroup']) && in_array('onlyForSubGroups', $this->data['report_for_subgroup'])?  '<printWhenExpression><![CDATA[!$P{SPLIT_QUESTION_LABEL}.isEmpty()]]></printWhenExpression>':"") ?>
	
	</reportElement>
	
	<subreportParameter name="CUSTOMER">
		<subreportParameterExpression><![CDATA[$P{CUSTOMER}]]></subreportParameterExpression>
	</subreportParameter>
	<subreportParameter name="DEFAULT_STYLE_FILE">
		<subreportParameterExpression><![CDATA[$P{DEFAULT_STYLE_FILE}]]></subreportParameterExpression>
	</subreportParameter>
	<subreportParameter name="REPORT_RESOURCE_BUNDLE">
		<subreportParameterExpression><![CDATA[$P{REPORT_RESOURCE_BUNDLE}]]></subreportParameterExpression>
	</subreportParameter>
	<subreportParameter name="Q_TEXT">
		<subreportParameterExpression><![CDATA["<?php echo $this->data['text']; ?>"]]></subreportParameterExpression>
	</subreportParameter>
    <dataSourceExpression><![CDATA[new net.sf.jasperreports.engine.JREmptyDataSource()]]></dataSourceExpression>
    <subreportExpression><![CDATA[$P{SUBREPORT_DIR}+"report5-text.jasper"]]></subreportExpression>
</subreport>