<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
	<head>	
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink()
			->appendStylesheet($this->baseUrl("css/global.css")); ?>
		<?php echo $this->headScript(); ?>
	</head> 
	
	<body>
		<div id="logo">
			<a href="<?php echo $this->baseUrl("/"); ?>">
				<img src="<?php echo $this->baseUrl("images/nivocer-logo.png"); ?>"/>
			</a>
		</div>
		<h1>Webenq 4</h1>
		<?php echo $this->layout()->content ?>
	</body>
</html>