<?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
            <?php echo $this->headMeta() ?>
            <?php echo $this->headLink() ?>
            <?php echo $this->jQuery() ?>
            <?php echo $this->headScript() ?>
            <?php echo $this->headTitle()?>
        </head>
        <body>
            <div id="header">
                <div id="logo">
                    <a href="<?php echo $this->baseUrl("/"); ?>">
                        <img src="<?php echo $this->baseUrl("images/nivocer-logo.png"); ?>"/>
                        <h1>Webenq 4</h1>
                    </a>
                </div>
                <div class="loading"><?php echo t('one moment please...'); ?></div>
                <?php echo $this->navigation()->menu(); ?>
                <?php echo $this->languageSelection; ?>
                <?php echo $this->messenger($this->messages); ?>
            </div>
            <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
            <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
                <div class="flash_messenger_success">
                <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                    <?php echo $msg ?>
                <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <?php if ($flashMessenger->setNamespace('error')->hasMessages()): ?>
                <div class="flash_messenger_error">
                <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                    <?php echo $msg ?>
                <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <div id="content">
                <?php echo $this->layout()->content ?>
            </div>
            <div id="footer">
            </div>
        </body>
    </html>