<a href="<?php echo $this->baseUrl('/answer-possibility/edit/id/' . $this->synonym->AnswerPossibilityText->AnswerPossibility->id); ?>">
    <?php echo t('back to answer possibility') . ' "' . $this->synonym->AnswerPossibilityText->text . '"'; ?>
</a>
<?php echo $this->form; ?>

<?php if ($this->answerPossibility): ?>
    <a href="<?php echo $this->baseUrl('/answer-possibility-synonym/add/id/' . $this->answerPossibility->AnswerPossibilityText[0]->id); ?>">
        <?php echo t('add synonym'); ?>
    </a>
    <table>
        <thead>
            <tr>
                <th>synoniem</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->answerPossibility->AnswerPossibilityText[0]->AnswerPossibilityTextSynonym as $answerPossibilityTextSynonym): ?>
                <tr>
                    <td>
                        <?php echo $synonym->text; ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->baseUrl('/answer-possibility-synonym/edit/id/' . $synonym->id); ?>">
                            <?php echo t('edit'); ?>
                        </a>
                        <a href="<?php echo $this->baseUrl('/answer-possibility-synonym/delete/id/' . $synonym->id); ?>">
                            <?php echo t('delete'); ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>