<?php

/**
 * Webenq_Model_Base_AnswerDomainItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * @property string $value
 * @property boolean $isNullValue
 * @property boolean $isActive
 * @property boolean $isHidden
 * @property Doctrine_Collection $AnswerDomain
 * @property Doctrine_Collection $AnswerDomainChoice
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_AnswerDomainItem extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('answer_domain_item');
        $this->hasColumn('label', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('isNullValue', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('isActive', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('isHidden', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Webenq_Model_AnswerDomain as AnswerDomain', array(
             'local' => 'id',
             'foreign' => 'answer_domain_item_id'));

        $this->hasMany('Webenq_Model_AnswerDomainChoice as AnswerDomainChoice', array(
             'local' => 'id',
             'foreign' => 'answer_domain_item_id'));

        $webenq4_template_i18n0 = new WebEnq4_Template_I18n(array(
             'fields' => 
             array(
              0 => 'label',
             ),
             ));
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             ));
        $this->actAs($webenq4_template_i18n0);
        $this->actAs($nestedset0);
    }
}