<?php

/**
 * Webenq_Model_Base_AnswerDomainChoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Webenq_Model_AnswerDomainItem $AnswerDomainItem
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_AnswerDomainChoice extends Webenq_Model_AnswerDomain
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Webenq_Model_AnswerDomainItem as AnswerDomainItem', array(
             'local' => 'answer_domain_item_id',
             'foreign' => 'id'));
    }
}