<?php

/**
 * Webenq_Model_Base_AnswerDomain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property array $validators
 * @property array $filters
 * @property array $options
 * @property string $type
 * @property integer $min_length
 * @property integer $max_length
 * @property float $min
 * @property float $max
 * @property integer $min_choices
 * @property integer $max_choices
 * 
 * @package    Webenq_Models
 * @subpackage ##SUBPACKAGE##
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_AnswerDomain extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('answer_domain');
        $this->hasColumn('validators', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('filters', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('options', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('min_length', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('max_length', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('min', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('max', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('min_choices', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('max_choices', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->setSubClasses(array(
             'Webenq_Model_AnswerDomainText' => 
             array(
              'type' => 'AnswerDomainText',
             ),
             'Webenq_Model_AnswerDomainNumeric' => 
             array(
              'type' => 'AnswerDomainNumeric',
             ),
             'Webenq_Model_AnswerDomainChoice' => 
             array(
              'type' => 'AnswerDomainChoice',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}