<?php

/**
 * Webenq_Model_Base_AnswerPossibilityNullValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $value
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_AnswerPossibilityNullValue extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('answerPossibilityNullValue');
        $this->hasColumn('value', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'length' => '64',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}