<?php

/**
 * Webenq_Model_Base_AnswerPossibilityGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $number
 * @property enum $measurement_level
 * @property Doctrine_Collection $AnswerPossibility
 * @property Doctrine_Collection $QuestionnaireQuestion
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_AnswerPossibilityGroup extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('answerPossibilityGroup');
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'length' => '64',
             ));
        $this->hasColumn('number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'notnull' => false,
             'length' => '4',
             ));
        $this->hasColumn('measurement_level', 'enum', 10, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'metric',
              1 => 'non-metric',
             ),
             'default' => 'non-metric',
             'notnull' => true,
             'length' => '10',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Webenq_Model_AnswerPossibility as AnswerPossibility', array(
             'local' => 'id',
             'foreign' => 'answerPossibilityGroup_id'));

        $this->hasMany('Webenq_Model_QuestionnaireQuestion as QuestionnaireQuestion', array(
             'local' => 'id',
             'foreign' => 'answerPossibilityGroup_id'));
    }
}