<?php

/**
 * Webenq_Model_Base_QuestionnairePageElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_QuestionnairePageElement extends Webenq_Model_QuestionnaireGroupElement
{
    public function setUp()
    {
        parent::setUp();
        
    }
}