<?php

/**
 * Webenq_Model_Base_QuestionnaireNode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $questionnaire_element_id
 * @property string $type
 * @property Webenq_Model_QuestionnaireElement $QuestionnaireElement
 * @property Doctrine_Collection $Questionnaire
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_QuestionnaireNode extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('questionnaire_node');
        $this->hasColumn('questionnaire_element_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'Webenq_Model_QuestionnaireGroupNode' => 
             array(
              'type' => 'QuestionnaireGroupNode',
             ),
             'Webenq_Model_QuestionnairePageNode' => 
             array(
              'type' => 'QuestionnairePageNode',
             ),
             'Webenq_Model_QuestionnaireQuestionNode' => 
             array(
              'type' => 'QuestionnaireQuestionNode',
             ),
             'Webenq_Model_QuestionnaireTextNode' => 
             array(
              'type' => 'QuestionnaireTextNode',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Webenq_Model_QuestionnaireElement as QuestionnaireElement', array(
             'local' => 'questionnaire_element_id',
             'foreign' => 'id'));

        $this->hasMany('Webenq_Model_Questionnaire as Questionnaire', array(
             'local' => 'id',
             'foreign' => 'questionnaire_node_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             ));
        $this->actAs($nestedset0);
    }
}