<?php

/**
 * Webenq_Model_Base_QuestionnaireElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $type
 * 
 * @package    Webenq_Models
 * @subpackage ##SUBPACKAGE##
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_QuestionnaireElement extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('questionnaire_element');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'Webenq_Model_QuestionnaireGroupElement' => 
             array(
              'type' => 'QuestionnaireGroupElement',
             ),
             'Webenq_Model_QuestionnairePageElement' => 
             array(
              'type' => 'QuestionnairePageElement',
             ),
             'Webenq_Model_QuestionnaireQuestionElement' => 
             array(
              'type' => 'QuestionnaireQuestionElement',
             ),
             'Webenq_Model_QuestionnaireTextElement' => 
             array(
              'type' => 'QuestionnaireTextElement',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}