<?php

/**
 * Webenq_Model_Base_QuestionnaireElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $text
 * @property integer $answer_domain_id
 * @property string $type
 * @property Webenq_Model_AnswerDomain $AnswerDomain
 * @property Doctrine_Collection $QuestionnaireNode
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_QuestionnaireElement extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('questionnaire_element');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('answer_domain_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'Webenq_Model_QuestionnaireGroupElement' => 
             array(
              'type' => 'QuestionnaireGroupElement',
             ),
             'Webenq_Model_QuestionnairePageElement' => 
             array(
              'type' => 'QuestionnairePageElement',
             ),
             'Webenq_Model_QuestionnaireQuestionElement' => 
             array(
              'type' => 'QuestionnaireQuestionElement',
             ),
             'Webenq_Model_QuestionnaireTextElement' => 
             array(
              'type' => 'QuestionnaireTextElement',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Webenq_Model_AnswerDomain as AnswerDomain', array(
             'local' => 'answer_domain_id',
             'foreign' => 'id'));

        $this->hasMany('Webenq_Model_QuestionnaireNode as QuestionnaireNode', array(
             'local' => 'id',
             'foreign' => 'questionnaire_element_id'));

        $webenq4_template_i18n0 = new WebEnq4_Template_I18n(array(
             'fields' => 
             array(
              0 => 'text',
             ),
             ));
        $this->actAs($webenq4_template_i18n0);
    }
}