<?php

/**
 * Webenq_Model_Base_QuestionnaireNode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $element_id
 * @property Doctrine_Collection $Questionnaire
 * 
 * @package    Webenq_Models
 * @subpackage ##SUBPACKAGE##
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_QuestionnaireNode extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('questionnaire_node');
        $this->hasColumn('element_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Webenq_Model_Questionnaire as Questionnaire', array(
             'local' => 'id',
             'foreign' => 'node_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             ));
        $this->actAs($nestedset0);
    }
}