<?php

/**
 * Webenq_Model_Base_ReportPresentation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $questionnaire_question_id
 * @property string $type
 * @property Webenq_Model_QuestionnaireQuestion $QuestionnaireQuestion
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_ReportPresentation extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('reportPresentation');
        $this->hasColumn('questionnaire_question_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'length' => '64',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Webenq_Model_QuestionnaireQuestion as QuestionnaireQuestion', array(
             'local' => 'questionnaire_question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE',
             'foreignKeyName' => 'reportPresentation_questionnaire_question_id_fk'));
    }
}