<?php

/**
 * Webenq_Model_Base_Respondent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $questionnaire_id
 * @property Webenq_Model_Questionnaire $Questionnaire
 * @property Doctrine_Collection $Answer
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_Respondent extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('respondent');
        $this->hasColumn('questionnaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Webenq_Model_Questionnaire as Questionnaire', array(
             'local' => 'questionnaire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE',
             'foreignKeyName' => 'respondent_questionnaire_id_fk'));

        $this->hasMany('Webenq_Model_Answer as Answer', array(
             'local' => 'id',
             'foreign' => 'respondent_id'));
    }
}