<?php echo $this->form ?>

<ul>
    <li>
        <a href="<?php echo $this->baseUrl('/questionnaire/xform/id/' . $this->id); ?>" title="<?php echo t('XForm download'); ?>">
            <?php echo t('XForm download'); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->baseUrl('/questionnaire/xform-data/id/' . $this->id); ?>" title="<?php echo t('XForm data download'); ?>">
            <?php echo t('XForm data download'); ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->baseUrl('/report/jrxml/id/' . $this->id); ?>" title="<?php echo t('JRXML download'); ?>">
            <?php echo t('JRXML download'); ?>
        </a>
    </li>
</ul>