<a id="edit_title" class="icon edit" href="#"></a>
<h1><?php echo $this->questionnaire['title']; ?></h1>
<?php echo $this->form ?>
<br clear="all" />

<div class="clear">
    <a class="ajax link add" href="<?= $this->baseUrl('/question/add/questionnaire_id/' . $this->questionnaire['id']) ?>" title="<?php echo _('nieuwe vraag toevoegen'); ?>">
        <?php echo _('nieuwe vraag toevoegen'); ?>
    </a>
</div>
<div class="clear">
    <a class="ajax link add" href="<?= $this->baseUrl('/questionnaire-question/add/questionnaire_id/' . $this->questionnaire['id']) ?>" title="<?php echo _('bestaande vraag toevoegen'); ?>">
        <?php echo _('bestaande vraag toevoegen'); ?>
    </a>
</div>
<div class="clear">
    <a class="link add add_page" href="#" title="<?php echo _('pagina toevoegen'); ?>">
        <?php echo _('pagina toevoegen'); ?>
    </a>
</div>

<div class="tabs">
    <ul>
        <?php for($page = 1; $page <= $this->totalPages; $page++): ?>
            <li>
                <a href="#page-<?php echo $page; ?>">
                    <?php echo _('pagina') . ' ' . $page; ?>
                </a>
            </li>
        <?php endfor; ?>
    </ul>
    <?php for($page = 1; $page <= $this->totalPages; $page++): ?>
        <div id="page-<?php echo $page; ?>">
            <a href="#" class="delete-page link delete">Deze pagina verwijderen</a>
            <div class="questions">
                <ul class="questions-list sortable droppable">
                    <?php
                        foreach ($this->questions as $key => $qq) {
                            if (($page === 1 && !isset($qq['CollectionPresentation'][0])) ||
                                $page === (int) $qq['CollectionPresentation'][0]['page'])
                            {
                                echo $this->questionElement($qq, $this->totalPages);
                                unset($this->questions[$key]);
                            }
                        }
                    ?>
                </ul>
            </div>
        </div>
    <?php endfor; ?>
</div>