<h1><?php echo $this->questionnaire->getTitle(); ?></h1>

<div class="clear" />
<a class="edit with_icon toggleform" href="#"><?php echo t('edit questionnaire properties'); ?></a>
<?php echo $this->propertiesForm ?>
</div>

<div class="tabs">
    <ul>
    <!-- page tab setup -->
<!-- //render via model (at this moment) -->
    <?php  echo $this->questionnaire->QuestionnaireNode->render('previewTab'); ?>

    <a  href="<?php echo $this->baseUrl('/questionnaire/add-page/id/' . $this->questionnaire['id']) ?>" title="<?php echo t('add page'); ?>">
        <?php echo t('New page'); ?>
    </a>
</ul>


<!-- content per page -->
<?php //walk through hierarchy in plugin, call render in model at the plugin ?>
<?php echo $this->questionnaireElement($this->questionnaire->QuestionnaireNode); ?>
<?php /* ?>
    <?php foreach ($this->questionnaire->QuestionnaireNode->getNode()->getChildren() as $group) : ?>
        <div id="<?php echo "group-".$group->id; ?>">
            <a href="#" class="delete-page link delete"><?php echo t('Delete this page'); ?></a>
            <div class="questions">
                <ul class="questions-list sortable droppable">
                    <?php
                        foreach ($group->getNode()->getChildren() as $qq) {
                             echo $qq->render('preview')." </br>";
                        }
                    ?>
                </ul>
            </div>
        </div>
    <?php endforeach; ?>
    <?php */ ?>
</div>