<a class="ajax link add" href="<?php echo $this->baseUrl('/questionnaire/add') ?>" title="<?php echo t('add questionnaire'); ?>">
    <?php echo t('add questionnaire'); ?>
</a>

<?php if (isset($this->questionnaires[0])): ?>
    <table>
        <thead>
            <tr>
                <th></th>
                <th><?php echo t('category'); ?></th>
                <th><?php echo t('title'); ?></th>
                <th><?php echo t('published'); ?></th>
                <th><?php echo t('actions'); ?></th>
            </tr>
        </thead>
        <tbody class="questionnaire sortable">
            <?php foreach ($this->questionnaires as $questionnaire): ?>
                <?php $meta = unserialize($questionnaire['meta']); ?>
                <tr id="<?php echo 'q_'.$questionnaire['id'] ?>">
                    <td><div class="handle"></div></td>
                    <td>
                        <?php
                        echo  $questionnaire->Category->getCategoryText()->text;


                        ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->baseUrl("/questionnaire/edit/id/" . $questionnaire['id']);?>">
                            <?php echo $questionnaire->getQuestionnaireTitle()->text; ?>
                        </a>
                    </td>
                    <td>
                        <?php
                        $publishedState=$questionnaire->getPublishedState();
                        if ($publishedState['activated'] && $publishedState['afterStart'] && $publishedState['beforeEnd']) {
                            echo '<div class="icon check" title="'.t('start date').": ". $questionnaire->date_start.
                            " ".t('end date').": ".$questionnaire->date_end.'">V</div>';
                       }else {
                           echo '<div class="icon delete" title="'.t('start date').": ". $questionnaire->date_start.
                           " ".t('end date').": ".$questionnaire->date_end.'">X</div>';
                       }
                        ?>
                    </td>
                    <td>
                        <a class="icon edit" title="<?php echo t('edit'); ?>" href="<?php echo $this->baseUrl("/questionnaire/edit/id/" . $questionnaire['id']);    ?>">&nbsp;</a>
                        <a class="icon delete" title="<?php echo t('delete'); ?>" href="<?php echo $this->baseUrl("/questionnaire/delete/id/" . $questionnaire['id']); ?>">&nbsp;</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <?php echo t('No questionnaires have been imported yet') ?>
<?php endif; ?>