<a class="ajax link add" href="<?php echo $this->baseUrl('/questionnaire/add') ?>" title="<?php echo t('add questionnaire'); ?>">
    <?php echo t('add questionnaire'); ?>
</a>

<?php if (isset($this->questionnaires[0])): ?>
    <table>
        <thead>
            <tr>
                <th class="move"></th>
                <th class="category"><?php echo t('category'); ?></th>
                <th class="title"><?php echo t('title'); ?></th>
                <th class="published"><?php echo t('published'); ?></th>
                <th class="actions"><?php echo t('actions'); ?></th>
            </tr>
        </thead>
        <tbody class="questionnaire sortable">
            <?php foreach ($this->questionnaires as $questionnaire): ?>
                <tr id="<?php echo 'q_'.$questionnaire['id'] ?>">
                    <td class="move"><div class="handle" title="Drag to sort questionnaires"></div></td>
                    <td class="category">
                        <?php
                        echo  $questionnaire->Category->getCategoryText()->text;
                        ?>
                    </td>
                    <td class="title">
                        <a href="<?php echo $this->baseUrl("/questionnaire/edit/id/" . $questionnaire['id']);?>">
                            <?php echo $questionnaire->getQuestionnaireTitle()->text; ?>
                        </a>
                    </td>
                    <td class="published">
                        <?php
                         if ($questionnaire->getPublishedState()['published']) { ?>
                            <a class="icon check" title="<?php echo t('start date').' '. $questionnaire->date_start.", ".
                            t('end date').': '.$questionnaire->date_end; ?>"></a>
                       <?php }else{ ?>
                            <div class="icon disable" title="<?php echo t('start date').' '. $questionnaire->date_start.", ".
                            t('end date').': '.$questionnaire->date_end; ?>"></div>
                        <?php }?>
                    </td>
                    <td class="action">
                        <a class="icon edit" title="<?php echo t('edit'); ?>" href="<?php echo $this->baseUrl("/questionnaire/edit/id/" . $questionnaire['id']);    ?>">&nbsp;</a>
                        <a class="icon delete" title="<?php echo t('delete'); ?>" href="<?php echo $this->baseUrl("/questionnaire/delete/id/" . $questionnaire['id']); ?>">&nbsp;</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <?php echo t('No questionnaires have been imported yet') ?>
<?php endif; ?>