<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="report1" pageWidth="<?php echo $this->pageWidth; ?>" pageHeight="<?php echo $this->pageHeight; ?>" columnWidth="555" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="10" isFloatColumnFooter="true" whenResourceMissingType="Key">
    <property name="ireport.zoom" value="1.5"/>
    <property name="ireport.x" value="0"/>
    <property name="ireport.y" value="0"/>
    <template><![CDATA[$P{DEFAULT_STYLE_FILE}]]></template>
    <parameter name="QUERY" class="java.lang.String" isForPrompting="false">
        <defaultValueExpression><![CDATA[]]></defaultValueExpression>
    </parameter>
    <parameter name="REPORT_IDENTIFIER" class="java.lang.String"/>
    <parameter name="DEFAULT_STYLE_FILE" class="java.lang.String" isForPrompting="false">
        <defaultValueExpression><![CDATA["it/bisi/resources/defaultStyle.jrtx"]]></defaultValueExpression>
    </parameter>
    <parameter name="SUBREPORT_DIR" class="java.lang.String" isForPrompting="false">
        <defaultValueExpression><![CDATA["it/bisi/resources/"]]></defaultValueExpression>
    </parameter>
    <parameter name="OUTPUT_DIR" class="java.lang.String" isForPrompting="false"/>
    <parameter name="TEXTS" class="java.util.HashMap" isForPrompting="false"/>
    <parameter name="CUSTOMER" class="java.lang.String">
        <defaultValueExpression><![CDATA["leeuwenburg"]]></defaultValueExpression>
    </parameter>
    <parameter name="GROUP_ROWS" class="java.lang.String" isForPrompting="false"/>
    <parameter name="GROUP_ROWS_VALUE" class="java.lang.String" isForPrompting="false"/>
    <parameter name="SPLIT_QUESTION_ID" class="java.lang.String" isForPrompting="false"/>
    <parameter name="SPLIT_VALUE" class="java.lang.String" isForPrompting="false"/>
    <parameter name="REPORT_TYPE" class="java.lang.String"/>
    <parameter name="GROUP_NAME" class="java.lang.String" isForPrompting="false"/>
    <parameter name="BOECODE" class="java.lang.String" isForPrompting="false"/>
    <parameter name="DOCENT" class="java.lang.String" isForPrompting="false"/>
    <parameter name="MODULE_NAME" class="java.lang.String" isForPrompting="false"/>
    <parameter name="COLOR_RANGE" class="java.util.HashMap" isForPrompting="false"/>
    <parameter name="RESPONSE" class="java.lang.Integer" isForPrompting="false"/>
    <parameter name="IMAGE_DIR" class="java.lang.String" isForPrompting="false">
        <defaultValueExpression><![CDATA["it/bisi/resources/"]]></defaultValueExpression>
    </parameter>
    <parameter name="RESPONSE_PERCENTAGE" class="java.lang.String" isForPrompting="false"/>
    <parameter name="TITLE" class="java.lang.String"/>
    <parameter name="START_DATE" class="java.lang.String" isForPrompting="false"/>
    <parameter name="END_DATE" class="java.lang.String" isForPrompting="false"/>
    <parameter name="COLOR_RANGE_ALTERNATE" class="java.util.HashMap" isForPrompting="false"/>
    <queryString>
        <![CDATA[$P!{QUERY}]]>
    </queryString>
    <field name="type" class="java.lang.String"/>
    <field name="group_id" class="java.lang.Integer"/>
    <variable name="GROUP_ROWS" class="java.lang.String">
        <variableExpression><![CDATA[$P{GROUP_ROWS}]]></variableExpression>
    </variable>
    <group name="group">
        <groupExpression><![CDATA[$F{group_id}]]></groupExpression>
        <groupHeader>
            <band/>
        </groupHeader>
        <groupFooter>
            <band/>
        </groupFooter>
    </group>
    <?php
        echo $this->render('questionnaire/jrxml/title.phtml');
        echo $this->render('questionnaire/jrxml/pageHeader.phtml');
        echo $this->render('questionnaire/jrxml/columnHeader.phtml');
        echo $this->render('questionnaire/jrxml/detail.phtml');
        echo $this->render('questionnaire/jrxml/columnFooter.phtml');
        echo $this->render('questionnaire/jrxml/pageFooter.phtml');
        echo $this->render('questionnaire/jrxml/summary.phtml');
    ?>
</jasperReport>