<?php foreach($this->questionnaire['QuestionnaireQuestion'] as $qq): ?>
    <?php if (isset($qq['Question']['QuestionText'][0])): ?>
        <strong><?php echo $qq['Question']['QuestionText'][0]['text']; ?></strong>
    <?php else: ?>
        <i><strong><?php echo _('No question text available for the current language'); ?></strong></i>
    <?php endif; ?>
    <div>
        <a class="toggle_answers" href="#"><?php echo _('Toon/verberg antwoorden'); ?></a>
        <ul class="answers">
            <?php $printFrequencyTable = false; ?>
            <?php foreach ($qq['Answer'] as $answer): ?>
                <li>
                    <?php
                        if ($answer['text']):
                            echo $answer['text'];
                        else:
                            $printFrequencyTable = true;
                            $l = $this->language($answer['AnswerPossibility']['AnswerPossibilityText'], $this->language);
                            if (isset($l['text'])):
                                echo $l['text'];
                            endif;
                        endif;
                    ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php if ($printFrequencyTable) echo $this->frequencyTable($qq); ?>
    </div>
<?php endforeach; ?>