<?php

/**
 * Webenq_Model_Base_Question_Closed_Scale_Seven
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    Webenq
 * @subpackage Models
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
abstract class Webenq_Model_Base_Question_Closed_Scale_Seven extends Webenq_Model_Question_Closed_Scale
{
    public function setUp()
    {
        parent::setUp();
        
    }
}