<div class="nav-link">
	<a href="<?php echo $this->baseUrl("/email/merge"); ?>">Rapporten samenvoegen voor hoofddocenten</a>
	<a href="<?php echo $this->baseUrl("/email/merge-extra"); ?>">Rapporten samenvoegen voor extra docenten</a>
	<a href="<?php echo $this->baseUrl("/email/merge-course"); ?>">Rapporten samenvoegen voor opleidingen</a>
</div>

<?php if (count($this->reports) === 0): ?>
	Er zijn nog geen rapporten gegenereerd.			
<?php else: ?>
	<table>
		<thead>
			<tr>
				<th>rapport</th>
				<th>klant</th>
				<th>docent</th>
				<th>email</th>
				<th>gemaild</th>
				<th>email verzenden</th>
				<th>rapport verwijderen</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->reports as $report): ?>
				<tr>
					<td>
						<a href="<?php echo $this->baseUrl("/reports/". $report->filename); ?>">
							<?php echo $report->filename; ?>
						</a>						
					</td>
					<td>
						<?php echo $report->customer; ?>
					</td>
					<td>
						<?php echo $report->teacher; ?>
					</td>
					<td>
						<?php echo $report->email; ?>
					</td>
					<td>
						<?php echo ($report->sent === '0') ? 'nee' : 'ja'; ?>
					</td>
					<td>
						<?php if ($report->email && $report->sent === '0'): ?>
							<a href="<?php echo $this->baseUrl("/email/send/id/" . $report->id); ?>">
								email verzenden
							</a>
						<?php endif; ?>					
					</td>
					<td>
						<a href="<?php echo $this->baseUrl("/email/del/id/" . $report->id); ?>">
							rapport verwijderen
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>