<?php

/**
 * Webenq_Model_AnswerPossibilityNullValue
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Webenq
 * @subpackage Models
 * @author     Bart Huttinga <b.huttinga@nivocer.com>
 * @version    SVN: $Id: AnswerPossibilityNullValue.php,v 1.2 2011/10/13 10:42:18 bart Exp $
 */
class Webenq_Model_AnswerPossibilityNullValue extends Webenq_Model_Base_AnswerPossibilityNullValue
{
    static protected $_nullValues = array();

    static public function getNullValues()
    {
        if (count(self::$_nullValues) === 0) {

            self::$_nullValues[] = '';

            $nullValues = Doctrine_Query::create()
                ->from('Webenq_Model_AnswerPossibilityNullValue')
                ->execute(null, Doctrine_Core::HYDRATE_ARRAY);

            foreach ($nullValues as $nullValue) {
                self::$_nullValues[] = strtolower($nullValue['value']);
            }
        }

        return self::$_nullValues;
    }
}