<?php

/**
 * Webenq_Model_AnswerDomainItem
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Webenq_Models
 * @subpackage
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
class Webenq_Model_AnswerDomainItem extends Webenq_Model_Base_AnswerDomainItem
{
    /**
     * Fills array with answer domain items, and adds translations
     *
     * @param bool $deep
     * @param bool $prefixKey Not used
     * @return array
     * @see Doctrine_Record::fromArray()
     */
    public function toArray($deep = true, $prefixKey = false)
    {
        $result = parent::toArray($deep, $prefixKey);

        if ($deep) {
            // @todo We should find a way to do this via the I18n behavior, of find out why 'deep=true' doesn't do this
            $result['Translation'] = $this->Translation->toArray();
        }

        return $result;
    }
}