<?php

/**
 * Webenq_Model_AnswerDomainText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Webenq_Models
 * @subpackage 
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
class Webenq_Model_AnswerDomainText extends Webenq_Model_Base_AnswerDomainText
{

}