<?php

/**
 * Webenq_Model_AnswerPossibilityText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Webenq
 * @subpackage Models
 * @author     Bart Huttinga <b.huttinga@nivocer.com>
 * @version    SVN: $Id: AnswerPossibilityText.php,v 1.1 2011/07/12 12:14:19 bart Exp $
 */
class Webenq_Model_AnswerPossibilityText extends Webenq_Model_Base_AnswerPossibilityText
{

}