<?php

/**
 * Webenq_Model_CategoryText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Webenq
 * @subpackage Models
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
class Webenq_Model_CategoryText extends Webenq_Model_Base_CategoryText
{

}