<?php

/**
 * Webenq_Model_MigrationVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Webenq
 * @subpackage Models
 * @author     Bart Huttinga <b.huttinga@nivocer.com>
 * @version    SVN: $Id: MigrationVersion.php,v 1.1 2011/10/27 16:34:01 bart Exp $
 */
class Webenq_Model_MigrationVersion extends Webenq_Model_Base_MigrationVersion
{

}