<?php

/**
 * Webenq_Model_QuestionnaireGroupNode
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Webenq_Models
 * @subpackage ##SUBPACKAGE##
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
class Webenq_Model_QuestionnaireGroupNode extends Webenq_Model_Base_QuestionnaireGroupNode
{
public function render($format)
    {
        switch ($format){
            case 'previewTab':
                // no render
                return '';
            break;
            default:
                $return=new WebEnq4_Form_Element_Note('dummy-'.$this->id);
                $return->setLabel('placeholder for group with id: '. $this->id);
                return $return;
            break;
        }
    }
}