<?php

/**
 * Webenq_Model_QuestionnaireTitle
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Webenq
 * @subpackage Models
 * @author     Bart Huttinga <b.huttinga@nivocer.com>
 * @version    SVN: $Id: QuestionnaireTitle.php,v 1.1 2011/10/27 12:55:21 bart Exp $
 */
class Webenq_Model_QuestionnaireTitle extends Webenq_Model_Base_QuestionnaireTitle
{

}