<?php

/**
 * Webenq_Model_QuestionnaireNode
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Webenq_Models
 * @subpackage ##SUBPACKAGE##
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
class Webenq_Model_QuestionnaireNode extends Webenq_Model_Base_QuestionnaireNode
{
    /*
     * Save this node element
     *
     * Check the linked QuestionnaireElement: if it has changes and is used in
     * more than one QuestionnaireNode, make a copy of the object and update the
     * reference to it
     * @todo check function
     *
     */
    public function xsave(Doctrine_Connection $conn = null)
    {
        if ($this->QuestionnaireElement->isModified()) {
            if (1 < Doctrine_Query::create()
                ->select('COUNT(id)')
                ->from('Webenq_Model_QuestionnaireNode qn')
                ->where('qn.questionnaire_element_id = ?', $this->QuestionnaireElement->id)->count()) {
                $this->QuestionnaireElement = clone $this->QuestionnaireElement;
                $this->QuestionnaireElement->save($conn);
                $this->element_id = $this->QuestionnaireElement->id;
            } else {
                $this->QuestionnaireElement->save($conn);

            }
        }
        parent::save($conn);
    }

    // Reorder the children
    public function reorderChildren($ordering)
    {
        // query findAll where id in $ordering
        // foreach result
        //     moveAsLastChildOf($this->id)
        //
        // cases:
        // - not all children of this node were given
        // - more nodes were given
        // - given nodes were not children of this node
        //   example: drag question from one Likert table into another
    }

    // prepare the output (
    //return  Zend_Form_Element_*
    public function render($format)
    {
        switch ($format){
            case 'previewTab':
                $return='';
                if ($this->getNode()->hasChildren()){
                    foreach ($this->getNode()->getChildren() as $group){
                        $return.=$group->render($format);
                    }
                }
                return $return;
            break;
            default:
                $return=new Zend_Form_Element_Text('dummy-'.$this->id);
                $return->setLabel($this->QuestionnaireElement->getTranslation('text'));
                return $return;
            break;
        }
    }
    public function toArray($deep = true, $prefixKey = false)
    {
        $result = parent::toArray($deep, $prefixKey);
        if (isset($this->id)) {
            $result['question']['id']=$this->id;
        }
        foreach ($this->QuestionnaireElement->Translation as $lang=>$translation) {
            if (isset($translation->text)) {
                //$result['question'][$lang] = $translation->text;
                $result['question']['text'][$lang] = $translation->text;
            }
        }

        if (isset($this->QuestionnaireElement->answer_domain_id)){
            $result['question']['reuse']=$this->QuestionnaireElement->answer_domain_id;
        }

        if (isset($this->QuestionnaireElement->AnswerDomain)){
            $result['answerOptions']['answersettings']=$this->QuestionnaireElement->AnswerDomain->toArray();
            $result['answerOptions']['answersettings']['name']=$this->QuestionnaireElement->AnswerDomain->getTranslation('name');
        }
        foreach ($this->QuestionnaireElement->options['answersettings'] as $key=>$value){
            $result['answerOptions']['answersettings'][$key]=$value;
        }
        if (isset($this->QuestionnaireElement->options['options'])){
            $result['options']=$this->QuestionnaireElement->options['options'];
        }
        return $result;
    }

    /*
     * untested
     */
    public function fromArray(array $array, $deep = true)
    {
        $language = Zend_Registry::get('Zend_Locale')->getLanguage();
        parent::fromArray($array, $deep);
            if (isset($array['question']['id'])) {
                $this->id=$array['question']['id'];
            }
            if (isset($array['question']) && is_array($array['question'])) {
            foreach ($array['question'] as $language => $text) {
                if ($text) {
                    $this->QuestionnaireElement->Translation[$language]->text = $text;
                }
            }
            if (isset($array['reuse'])){
                $this->QuestionnaireElement->answer_domain_id=$array['reuse'];
            }
            //changes need to be stored in options, not in aswerdomain.
            if (isset($array['answerOptions']['answersettings'])){
                $this->QuestionnaireElement->options['answersettings']=$array['answerOptions']['answersettings'];
            }
            if (isset($array['answerOptions']['answersettings']['name'])){
                $this->QuestionnaireElement->AnswerDomain->Translation[$language]->name=$array['answerOptions']['answersettings']['name'];
            }

            $result['answerOptions']['answersettings']['name']=$this->QuestionnaireElement->AnswerDomain->getTranslation('name');
        }
    }

}