<?php

/**
 * Webenq_Model_QuestionnaireLikertNode
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Webenq_Models
 * @subpackage
 * @author     Nivocer <webenq@nivocer.com>
 * @version    SVN: $Id: Builder.php,v 1.2 2011/07/12 13:39:03 bart Exp $
 */
class Webenq_Model_QuestionnaireLikertNode extends Webenq_Model_Base_QuestionnaireLikertNode
{
    public function render($format)
    {
        switch ($format){
            case 'previewTab':
                return "";
            break;
            default:
                //return a note with the text
                $return=new WebEnq4_Form_Element_Note('note-'.$this->id);
                $return->setLabel($this->QuestionnaireElement->getTranslation('text'));
                return $return;
                //return parent::render($format);
            break;
        }
    }
}