<?php

/**
 * Webenq_Model_Resource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Webenq
 * @subpackage Models
 * @author     Bart Huttinga <b.huttinga@nivocer.com>
 * @version    SVN: $Id: Resource.php,v 1.1 2011/07/12 12:14:18 bart Exp $
 */
class Webenq_Model_Resource extends Webenq_Model_Base_Resource
{

}