<?php

/**
 * Webenq_Model_Role
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Webenq
 * @subpackage Models
 * @author     Bart Huttinga <b.huttinga@nivocer.com>
 * @version    SVN: $Id: Role.php,v 1.1 2011/07/12 12:14:16 bart Exp $
 */
class Webenq_Model_Role extends Webenq_Model_Base_Role
{
    public static function getAllAsArray()
    {
        $roles = Doctrine_Core::getTable('Webenq_Model_Role')->findAll();

        $retVal = array();
        foreach ($roles as $role) {
            $retVal[$role->id] = $role->name;
        }

        return $retVal;
    }
}