<?php

/**
 * Webenq_Model_RoleResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Webenq
 * @subpackage Models
 * @author     Bart Huttinga <b.huttinga@nivocer.com>
 * @version    SVN: $Id: RoleResource.php,v 1.1 2011/07/12 12:14:16 bart Exp $
 */
class Webenq_Model_RoleResource extends Webenq_Model_Base_RoleResource
{

}