<?php

/**
 * Webenq_Model_Session
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Webenq
 * @subpackage Models
 * @author     Bart Huttinga <b.huttinga@nivocer.com>
 * @version    SVN: $Id: Session.php,v 1.1 2011/10/28 13:01:40 bart Exp $
 */
class Webenq_Model_Session extends Webenq_Model_Base_Session
{

}