<?php

/**
 * Webenq_Model_User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Webenq
 * @subpackage Models
 * @author     Bart Huttinga <b.huttinga@nivocer.com>
 * @version    SVN: $Id: User.php,v 1.1 2011/07/12 12:14:18 bart Exp $
 */
class Webenq_Model_User extends Webenq_Model_Base_User
{
    static public function login($username, $password)
    {
        $authAdapter = new ZendDoctrine_Auth_Adapter_Doctrine(
            'Webenq_Model_User',
            'username',
            'password',
            'MD5'
        );

        $result = $authAdapter
            ->setIdentity($username)
            ->setCredential($password)
            ->authenticate();

        $auth = Zend_Auth::getInstance();
        if ($auth->hasIdentity()) $auth->clearIdentity();

        if ($result->isValid()) {
            $user = $authAdapter->getResult();
            $user->lastlogin = date('Y-m-d H:i:s');
            $user->save();

            $auth->getStorage()
                ->write($authAdapter->getFilteredResult(null, 'password'));

            return true;
        }

           return false;
    }
}