<h2>Labels schaalvragen (<?php echo $this->language; ?>)</h2>

<div class="nav-link">
	<a href="<?php echo $this->baseUrl("/"); ?>">Front page</a>
	<a href="<?php echo $this->baseUrl("/scale-values/add/language/" . $this->language); ?>">Waarde toevoegen</a>
	<?php if ($this->language !== 'nl'): ?>
		<a href="<?php echo $this->baseUrl("scale-values/index/language/nl"); ?>">Labels schaalvragen (nl)</a>
	<?php endif; ?>
	<?php if ($this->language !== 'en'): ?>
		<a href="<?php echo $this->baseUrl("scale-values/index/language/en"); ?>">Labels schaalvragen (en)</a>
	<?php endif; ?>
</div>

<?php if ($this->scaleValues && $this->scaleValues->count() > 0): ?>
	<table>
		<thead>
			<tr>
				<th>label</th>
				<th>waarde</th>
				<th>vraagtype</th>
				<th>bewerken</th>
				<th>verwijderen</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->scaleValues as $value): ?>
				<tr>
					<td>
						<?php echo $value->label; ?>
					</td>
					<td>
						<?php echo $value->value; ?>
					</td>
					<td>
						<?php echo $value->question_type; ?>
					</td>
					<td>
						<a href="<?php echo $this->baseUrl("/scale-values/edit/id/" . $value->id); ?>">
							bewerken
						</a>					
					</td>
					<td>
						<a href="<?php echo $this->baseUrl("/scale-values/del/id/" . $value->id); ?>">
							verwijderen
						</a>					
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else: ?>
	Er zijn nog geen schaalwaarden opgegeven.			
<?php endif; ?>