<h1>Rapport</h1>

<div class="nav-link">
	<a href="<?php echo $this->baseUrl("/"); ?>">
		Front page
	</a>
</div>

<?php if ($this->output): ?>
	<div>
		<p>Er is een probleem opgetreden bij het genereren van het rapport. Zie onderstaande melding voor details.</p>
		<pre><?php echo $this->output; ?></pre>
	</div>
<?php else: ?>
	<div>
		<p>Het rapport is gegenereerd en opgeslagen. Klik op onderstaande link om het rapport te bekijken.</p>
		<a href="<?php echo $this->baseUrl("reports/" . $this->file); ?>">
			<?php echo $this->file; ?>
		</a>
	</div>
<?php endif; ?>