<p>
    <a class="icon edit" title="<?php echo t('gebruikers beheren'); ?>" href="<?php echo $this->baseUrl('/user/user') ?>">&nbsp;</a>
    <a href="<?php echo $this->baseUrl('/user/user') ?>"><?php echo t('gebruikers beheren'); ?></a>
</p>

<p>
    <a class="icon edit" title="<?php echo t('rollen beheren'); ?>" href="<?php echo $this->baseUrl('/user/role') ?>">&nbsp;</a>
    <a href="<?php echo $this->baseUrl('/user/role') ?>"><?php echo t('rollen beheren'); ?></a>
</p>

<?php echo $this->form; ?>