<p>
    <a class="icon edit" title="<?php echo t('manage users'); ?>" href="<?php echo $this->baseUrl('/user/user') ?>">&nbsp;</a>
    <a href="<?php echo $this->baseUrl('/user/user') ?>"><?php echo t('manage users'); ?></a>
</p>

<p>
    <a class="icon edit" title="<?php echo t('manage roles'); ?>" href="<?php echo $this->baseUrl('/user/role') ?>">&nbsp;</a>
    <a href="<?php echo $this->baseUrl('/user/role') ?>"><?php echo t('manage roles'); ?></a>
</p>

<?php echo $this->form; ?>