<p>
    <a class="icon edit" title="<?php echo _('gebruikers beheren'); ?>" href="<?= $this->baseUrl('/user/user') ?>">&nbsp;</a>
    <a href="<?= $this->baseUrl('/user/user') ?>"><?php echo _('gebruikers beheren'); ?></a>
</p>

<p>
    <a class="icon edit" title="<?php echo _('rollen beheren'); ?>" href="<?= $this->baseUrl('/user/role') ?>">&nbsp;</a>
    <a href="<?= $this->baseUrl('/user/role') ?>"><?php echo _('rollen beheren'); ?></a>
</p>

<?php echo $this->form; ?>