<a class="link edit" title="<?php echo t('manage users'); ?>" href="<?php echo $this->baseUrl('/user/user') ?>">
	<?php echo t('manage users'); ?>
</a>
<a class="link edit" title="<?php echo t('manage permissions'); ?>" href="<?php echo $this->baseUrl('/user/permission') ?>">
	<?php echo t('manage permissions'); ?>
</a>

<table>
    <thead>
        <tr>
            <th><?php echo t('role'); ?></th>
            <th class="actions">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->roles as $role): ?>
            <tr>
                <?php if (isset($this->editForm) && $this->editForm->id->getValue() == $role->id): ?>
                    <td>
                        <?php echo $this->editForm; ?>
                    </td>
                <?php elseif (isset($this->deleteForm) && $this->deleteForm->id->getValue() == $role->id): ?>
                    <td>
                        <?php echo $this->deleteForm; ?>
                    </td>
                <?php else: ?>
                    <td>
                        <?php echo $role->name; ?>
                    </td>
                <?php endif; ?>
                <td>
                    <a class="icon edit" href="<?php echo $this->baseUrl('/user/role/edit/' . $role->id); ?>"></a>
                    <a class="icon delete" href="<?php echo $this->baseUrl('/user/role/delete/' . $role->id); ?>"></a>
                </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td colspan="2"><?php echo $this->addForm; ?></td>
        </tr>
    </tbody>
</table>