<p>
	<a class="icon edit" title="<?php echo _('gebruikers beheren'); ?>" href="<?= $this->baseUrl('/user/user') ?>">&nbsp;</a>
	<a href="<?= $this->baseUrl('/user/user') ?>"><?php echo _('gebruikers beheren'); ?></a>
</p>

<p>
	<a class="icon edit" title="<?php echo _('rechten beheren'); ?>" href="<?= $this->baseUrl('/user/permission') ?>">&nbsp;</a>
	<a href="<?= $this->baseUrl('/user/permission') ?>"><?php echo _('rechten beheren'); ?></a>
</p>

<table>
	<thead>
		<tr>
			<th>rol</th>
			<th class="actions">acties</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->roles as $role): ?>
			<tr>
				<?php if (isset($this->editForm) && $this->editForm->id->getValue() == $role->id): ?>
					<td>
						<?php echo $this->editForm; ?>
					</td>
				<?php elseif (isset($this->deleteForm) && $this->deleteForm->id->getValue() == $role->id): ?>
					<td>
						<?php echo $this->deleteForm; ?>
					</td>
				<?php else: ?>
					<td>
						<?php echo $role->name; ?>
					</td>
				<?php endif; ?>
				<td>
					<a class="icon edit" href="<?php echo $this->baseUrl('/user/role/edit/' . $role->id); ?>"></a>
					<a class="icon delete" href="<?php echo $this->baseUrl('/user/role/delete/' . $role->id); ?>"></a>
				</td>
			</tr>
		<?php endforeach; ?>
		<tr>
			<td colspan="2"><?php echo $this->addForm; ?></td>
		</tr>
	</tbody>
</table>