<a class="link edit" title="<?php echo t('manage roles'); ?>" href="<?php echo $this->baseUrl('/user/role') ?>">
    <?php echo t('manage roles'); ?>
</a>
<a class="link edit" title="<?php echo t('manage permissions'); ?>" href="<?php echo $this->baseUrl('/user/permission') ?>">
	<?php echo t('manage permissions'); ?>
</a>

<table>
    <thead>
        <tr>
            <th><?php echo t('username'); ?></th>
            <th><?php echo t('name'); ?></th>
            <th><?php echo t('role'); ?></th>
            <th class="actions">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->users as $user): ?>
            <tr>
                <?php if (isset($this->editForm) && $this->editForm->id->getValue() == $user->id): ?>
                    <td colspan="3">
                        <?php echo $this->editForm; ?>
                    </td>
                <?php elseif (isset($this->deleteForm) && $this->deleteForm->id->getValue() == $user->id): ?>
                    <td colspan="3">
                        <?php echo $this->deleteForm; ?>
                    </td>
                <?php else: ?>
                    <td>
                        <?php echo $user->username; ?>
                    </td>
                    <td>
                        <?php echo $user->fullname; ?>
                    </td>
                    <td>
                        <?php echo $user->Role->name; ?>
                    </td>
                <?php endif; ?>
                <td>
                    <a class="icon edit" href="<?php echo $this->baseUrl('/user/user/edit/' . $user->id); ?>" title="<?php echo t('edit'); ?>"></a>
                    <a class="icon delete" href="<?php echo $this->baseUrl('/user/user/delete/' . $user->id); ?>" title="<?php echo t('delete'); ?>"></a>
                </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td colspan="4"><?php echo $this->addForm; ?></td>
        </tr>
    </tbody>
</table>