<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('resource', 'unique-name', array(
             'fields' => 'name',
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('resource', 'unique-name', array(
             'fields' => 'name',
             'type' => 'unique',
             ));
    }
}