<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('questionnaire', 'weight', 'int', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('questionnaire', 'weight');
    }
}