<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('questionnaire', 'date_start', 'timestamp', '25', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '2012-01-01 00:00:00',
             'notnull' => '1',
             'autoincrement' => '',
             ));
        $this->changeColumn('questionnaire', 'date_end', 'timestamp', '25', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '2050-01-01 00:00:00',
             'notnull' => '1',
             'autoincrement' => '',
             ));
    }

    public function down()
    {

    }
}