<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('categoryText', 'categoryText_category_id_fk', array(
             'name' => 'categoryText_category_id_fk',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('questionnaire', 'questionnaire_category_id_category_id', array(
             'name' => 'questionnaire_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('categoryText', 'categoryText_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('questionnaire', 'questionnaire_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('categoryText', 'categoryText_category_id_fk');
        $this->dropForeignKey('questionnaire', 'questionnaire_category_id_category_id');
        $this->removeIndex('categoryText', 'categoryText_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('questionnaire', 'questionnaire_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
    }
}