<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('category', 'weight', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'default' => '0',
             'notnull' => '1',
             'autoincrement' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('category', 'weight');
    }
}