<?php if ($this->filename): ?>
    <a href="<?php echo $this->baseUrl($this->filename); ?>">
        <?php echo $this->filename; ?> is gegenereerd<br/>
    </a>
<?php endif; ?>

<?php echo $this->form->render(); ?>

<?php if ($this->errors): ?>
    <ul class="errors">
        <?php foreach ($this->errors as $error): ?>
            <li><?php echo $error; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

